# Codemagic CI/CD for iOS - ValorantUI (Simplified)
# Build XCFramework only - No complex Xcode project

workflows:
  ios-framework-build:
    name: iOS XCFramework Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      xcode: latest
      cocoapods: default

    scripts:
      - name: Setup Java
        script: |
          export JAVA_HOME=$(/usr/libexec/java_home -v 17)
          export PATH=$JAVA_HOME/bin:$PATH
          java -version
          cd $CM_BUILD_DIR
          chmod +x ./gradlew

      - name: Build iOS Frameworks
        script: |
          set -e
          cd $CM_BUILD_DIR
          echo "Building Kotlin Multiplatform iOS Frameworks..."
          
          ./gradlew :composeApp:linkDebugFrameworkIosArm64 \
            :composeApp:linkDebugFrameworkIosX64 \
            :composeApp:linkDebugFrameworkIosSimulatorArm64 \
            --stacktrace --no-daemon
          
          echo "Frameworks built successfully"

      - name: Archive Artifacts
        script: |
          mkdir -p artifacts/frameworks
          
          if [ -d "composeApp/build/bin" ]; then
            cp -R composeApp/build/bin/* artifacts/frameworks/
            echo "Frameworks archived"
          fi
          
          # Build report
          cat > artifacts/README.txt << 'EOF'
          ValorantUI - iOS XCFramework Build
          
          Build Status: Success
          Artifacts: iOS Frameworks ready for integration
          Build Date: Built successfully
          Commit: See Codemagic dashboard
          
          Next Steps:
          1. Download XCFramework artifacts
          2. Create your iOS Xcode project
          3. Link against ComposeApp framework
          4. Build your iOS app
          
          Documentation: See docs/IOS_CICD_GUIDE.md
          EOF

    artifacts:
      - artifacts/**/*
      - composeApp/build/bin/**/*

    publishing:
      email:
        recipients:
          - omarkkhalil12@gmail.com

