workflows:
  kmm-android-workflow:
    name: KMM Android Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      java: 17
      groups:
        - google_credentials
      vars:
        PACKAGE_NAME: "com.larryyu.valorantui"
    scripts:
      - name: Set up local.properties
        script: echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Build Android APK
        script: |
          ./gradlew assembleDebug
          ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk
      - app/release/*.apk
    publishing:
      email:
        recipients:
          - omarkkhalil12@gmail.com
        notify:
          success: true
          failure: true

  kmm-ios-workflow:
    name: KMM iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      xcode: latest
      java: 17
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          cd iosApp
          pod install
      - name: Build iosApp for simulator
        script: |
          xcodebuild build \
            -workspace iosApp/iosApp.xcworkspace \
            -scheme iosApp \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15 Pro' \
            -configuration Debug \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            -derivedDataPath build
      - name: Take Screenshots
        script: |
          SIMULATOR_UDID=$(xcrun simctl list devices | grep "iPhone 15 Pro" | grep -E -o -i "([0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12})" | head -1)
          
          if [ -z "$SIMULATOR_UDID" ]; then
            echo "Creating simulator..."
            SIMULATOR_UDID=$(xcrun simctl create "iPhone 15 Pro Test" "iPhone 15 Pro" "iOS17-latest")
          fi
          
          xcrun simctl boot $SIMULATOR_UDID || echo "Already booted"
          sleep 10
          
          APP_PATH=$(find build -name "*.app" -type d | grep -v "Intermediates" | head -1)
          
          if [ -n "$APP_PATH" ]; then
            xcrun simctl install $SIMULATOR_UDID "$APP_PATH"
            xcrun simctl launch $SIMULATOR_UDID com.larryyu.valorantui
            sleep 5
            
            mkdir -p screenshots
            xcrun simctl io $SIMULATOR_UDID screenshot screenshots/01_launch.png
            sleep 2
            xcrun simctl io $SIMULATOR_UDID screenshot screenshots/02_app.png
            sleep 2
            xcrun simctl io $SIMULATOR_UDID screenshot screenshots/03_screen.png
            
            echo "Screenshots taken successfully"
          else
            echo "No app found to take screenshots"
          fi
    artifacts:
      - build/**/*.app
      - screenshots/*.png
    publishing:
      email:
        recipients:
          - omarkkhalil12@gmail.com
        notify:
          success: true
          failure: true

