# 🍎 Codemagic CI/CD for iOS - ValorantUI

workflows:
  # ==========================================
  # Workflow 1: iOS Simulator Build (NO SIGNING REQUIRED)
  # ==========================================
  ios-simulator-workflow:
    name: iOS Simulator Build (No Signing)
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_WORKSPACE: "iosApp/iosApp.xcworkspace"
        XCODE_SCHEME: "iosApp"
      xcode: latest
      cocoapods: default

    scripts:
      - name: Show Xcode version
        script: |
          xcodebuild -version
          xcrun simctl list devices

      - name: Setup Java Environment
        script: |
          # Codemagic already has Java pre-installed
          export JAVA_HOME=$(/usr/libexec/java_home -v 17 2>/dev/null || /usr/libexec/java_home)
          export PATH=$JAVA_HOME/bin:$PATH
          
          java -version
          echo "JAVA_HOME: $JAVA_HOME"

      - name: Build Kotlin Multiplatform Framework
        script: |
          set -e  # Exit on error
          set -x  # Print commands
          
          cd $CM_BUILD_DIR
          
          # Make gradlew executable
          chmod +x ./gradlew
          
          # Clean build
          ./gradlew clean || echo "Clean failed, continuing..."
          
          # Build XCFramework (with more verbose output)
          ./gradlew :composeApp:assembleXCFramework \
            --stacktrace \
            --info \
            --no-daemon
          
          # Verify build output
          if [ -d "composeApp/build/XCFrameworks" ]; then
            echo "✅ XCFramework built successfully"
            ls -la composeApp/build/XCFrameworks/
          else
            echo "❌ XCFramework build failed - directory not found"
            echo "Searching for any XCFramework..."
            find . -name "*.xcframework" -type d || echo "No XCFramework found"
            exit 1
          fi

      - name: Check for Xcode project
        script: |
          # Check if iosApp exists
          if [ -d "iosApp" ] && [ -f "iosApp/iosApp.xcodeproj/project.pbxproj" ]; then
            echo "✅ Found Xcode project"
            export HAS_XCODE_PROJECT=true
          elif [ -d "iosApp" ] && [ -f "iosApp/iosApp.xcworkspace/contents.xcworkspacedata" ]; then
            echo "✅ Found Xcode workspace"
            export HAS_XCODE_PROJECT=true
          else
            echo "⚠️ No Xcode project found"
            echo "This is OK - we'll just build the XCFramework"
            export HAS_XCODE_PROJECT=false
          fi

      - name: Build for iOS Simulator (Optional)
        script: |
          # Only build if Xcode project exists
          if [ -d "iosApp" ] && ([ -f "iosApp/iosApp.xcodeproj/project.pbxproj" ] || [ -f "iosApp/iosApp.xcworkspace/contents.xcworkspacedata" ]); then
            echo "Building iOS app..."
            
            cd iosApp
            
            # Determine if we have workspace or project
            if [ -f "iosApp.xcworkspace/contents.xcworkspacedata" ]; then
              BUILD_TARGET="-workspace iosApp.xcworkspace"
            else
              BUILD_TARGET="-project iosApp.xcodeproj"
            fi
            
            # Build for simulator - NO SIGNING REQUIRED
            xcodebuild build \
              $BUILD_TARGET \
              -scheme iosApp \
              -sdk iphonesimulator \
              -destination 'platform=iOS Simulator,name=iPhone 15 Pro' \
              -configuration Debug \
              CODE_SIGN_IDENTITY="" \
              CODE_SIGNING_REQUIRED=NO \
              CODE_SIGNING_ALLOWED=NO \
              -derivedDataPath $CM_BUILD_DIR/build \
              || echo "⚠️ Xcode build failed, continuing with XCFramework only"
            
            cd ..
            echo "✅ iOS app build attempted"
          else
            echo "⚠️ Skipping iOS app build - no Xcode project found"
            echo "✅ XCFramework is available for integration"
          fi

      - name: Take Screenshots on Simulator (Optional)
        script: |
          # Only take screenshots if app was built
          APP_PATH=$(find $CM_BUILD_DIR/build -name "*.app" -type d 2>/dev/null | grep -v "Intermediates" | head -1)
          
          if [ -n "$APP_PATH" ]; then
            echo "Found app at: $APP_PATH"
            
            # Boot simulator
            SIMULATOR_NAME="iPhone 15 Pro"
            xcrun simctl boot "$SIMULATOR_NAME" 2>/dev/null || echo "Simulator already booted or boot failed"
            
            # Wait for boot
            sleep 10
            
            # Install app
            xcrun simctl install booted "$APP_PATH" || echo "Install failed"
            
            # Launch app
            BUNDLE_ID="com.larryyu.valorantui"
            xcrun simctl launch booted $BUNDLE_ID || echo "Launch failed"
            
            # Take screenshots
            sleep 5
            mkdir -p screenshots
            xcrun simctl io booted screenshot screenshots/01_launch.png || echo "Screenshot failed"
            
            echo "✅ Screenshot process completed"
          else
            echo "⚠️ No .app found - creating placeholder screenshots"
            mkdir -p screenshots
            echo "No iOS app built - XCFramework only" > screenshots/README.txt
            echo "This is expected for Kotlin Multiplatform framework-only builds" >> screenshots/README.txt
          fi

      - name: Archive build artifacts
        script: |
          mkdir -p artifacts
          
          # Archive .app if exists
          APP_COUNT=$(find $CM_BUILD_DIR/build -name "*.app" -type d 2>/dev/null | grep -v "Intermediates" | wc -l)
          if [ "$APP_COUNT" -gt 0 ]; then
            echo "Archiving $APP_COUNT app(s)..."
            find $CM_BUILD_DIR/build -name "*.app" -type d 2>/dev/null | grep -v "Intermediates" | while read app; do
              cp -R "$app" artifacts/ 2>/dev/null || echo "Failed to copy $app"
            done
          else
            echo "⚠️ No .app bundles found"
          fi
          
          # Archive XCFramework (MAIN ARTIFACT)
          if [ -d "composeApp/build/XCFrameworks" ]; then
            echo "✅ Archiving XCFramework..."
            cp -R composeApp/build/XCFrameworks artifacts/
            
            # Create info file
            echo "ValorantUI - Kotlin Multiplatform XCFramework" > artifacts/BUILD_INFO.txt
            echo "Build Date: $(date)" >> artifacts/BUILD_INFO.txt
            echo "Commit: $CM_COMMIT" >> artifacts/BUILD_INFO.txt
            ls -lh artifacts/XCFrameworks/ >> artifacts/BUILD_INFO.txt
          else
            echo "❌ XCFramework not found!"
            exit 1
          fi
          
          echo "✅ Artifacts prepared successfully"
          ls -la artifacts/

    artifacts:
      - artifacts/**/*.app
      - artifacts/XCFrameworks/**/*
      - screenshots/*.png
      - build/**/*.xcarchive

    publishing:
      email:
        recipients:
          - omarkkhalil12@gmail.com
        notify:
          success: true
          failure: true

      # No App Store publishing (requires signing)
      # slack:
      #   channel: '#ios-builds'
      #   notify_on_build_start: false


  # ==========================================
  # Workflow 2: iOS App Store Build (REQUIRES APPLE DEVELOPER)
  # ==========================================
  ios-appstore-workflow:
    name: iOS App Store Build (With Signing)
    max_build_duration: 120
    instance_type: mac_mini_m1
    # ⚠️ ONLY ENABLE THIS IF YOU HAVE APPLE DEVELOPER ACCOUNT
    # integrations:
    #   app_store_connect: ValorantUI
    environment:
      # ios_signing:
      #   distribution_type: app_store
      #   bundle_identifier: com.larryyu.valorantui
      vars:
        XCODE_WORKSPACE: "iosApp/iosApp.xcworkspace"
        XCODE_SCHEME: "iosApp"
      xcode: latest
      cocoapods: default

    triggering:
      events:
        - tag
      branch_patterns:
        - pattern: 'release/*'
      cancel_previous_builds: true

    scripts:
      - name: Placeholder for App Store Build
        script: |
          echo "⚠️ This workflow requires:"
          echo "1. Apple Developer Account ($99/year)"
          echo "2. App Store Connect API Key"
          echo "3. Signing certificates"
          echo ""
          echo "For showcase/portfolio, use 'ios-simulator-workflow' instead"
          exit 0

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - omarkkhalil12@gmail.com

