# 🍎 Codemagic CI/CD for iOS - ValorantUI

workflows:
  # ==========================================
  # Workflow 1: iOS Simulator Build (NO SIGNING REQUIRED)
  # ==========================================
  ios-simulator-workflow:
    name: iOS Simulator Build (No Signing)
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_WORKSPACE: "iosApp/iosApp.xcworkspace"
        XCODE_SCHEME: "iosApp"
      xcode: latest
      cocoapods: default

    scripts:
      - name: Show Xcode version
        script: |
          xcodebuild -version
          xcrun simctl list devices

      - name: Install Java (for Gradle)
        script: |
          brew install openjdk@17
          sudo ln -sfn /opt/homebrew/opt/openjdk@17/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk-17.jdk
          export JAVA_HOME=$(/usr/libexec/java_home -v 17)

      - name: Build Kotlin Multiplatform Framework
        script: |
          cd $CM_BUILD_DIR
          chmod +x ./gradlew
          ./gradlew :composeApp:assembleXCFramework
          echo "✅ XCFramework built successfully"
          ls -la composeApp/build/XCFrameworks/

      - name: Create Xcode project (if needed)
        script: |
          # If no Xcode project exists, create basic one
          if [ ! -d "iosApp" ]; then
            echo "⚠️ No iosApp directory found. Creating basic structure..."
            mkdir -p iosApp
          fi

      - name: Build for iOS Simulator (No Signing)
        script: |
          # Build for simulator - NO SIGNING REQUIRED
          xcodebuild build \
            -scheme iosApp \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15 Pro' \
            -configuration Debug \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            -derivedDataPath $CM_BUILD_DIR/build
          
          echo "✅ Simulator build completed!"

      - name: Take Screenshots on Simulator
        script: |
          # Boot simulator
          xcrun simctl boot "iPhone 15 Pro" || echo "Already booted"
          
          # Wait for boot
          sleep 10
          
          # Install app on simulator
          APP_PATH=$(find $CM_BUILD_DIR/build -name "*.app" | head -1)
          if [ -n "$APP_PATH" ]; then
            xcrun simctl install booted "$APP_PATH"
            
            # Launch app
            BUNDLE_ID="com.larryyu.valorantui"
            xcrun simctl launch booted $BUNDLE_ID
            
            # Take screenshots
            sleep 5
            mkdir -p screenshots
            xcrun simctl io booted screenshot screenshots/01_launch.png
            
            echo "✅ Screenshots taken!"
          else
            echo "⚠️ App not found, skipping screenshot"
          fi

      - name: Archive build artifacts
        script: |
          # Find and archive the .app bundle
          mkdir -p artifacts
          find $CM_BUILD_DIR/build -name "*.app" -exec cp -R {} artifacts/ \;
          
          # Archive XCFramework
          if [ -d "composeApp/build/XCFrameworks" ]; then
            cp -R composeApp/build/XCFrameworks artifacts/
          fi
          
          echo "✅ Artifacts prepared"

    artifacts:
      - artifacts/**/*.app
      - artifacts/XCFrameworks/**/*
      - screenshots/*.png
      - build/**/*.xcarchive

    publishing:
      email:
        recipients:
          - omarkkhalil12@gmail.com
        notify:
          success: true
          failure: true

      # No App Store publishing (requires signing)
      # slack:
      #   channel: '#ios-builds'
      #   notify_on_build_start: false


  # ==========================================
  # Workflow 2: iOS App Store Build (REQUIRES APPLE DEVELOPER)
  # ==========================================
  ios-appstore-workflow:
    name: iOS App Store Build (With Signing)
    max_build_duration: 120
    instance_type: mac_mini_m1
    # ⚠️ ONLY ENABLE THIS IF YOU HAVE APPLE DEVELOPER ACCOUNT
    # integrations:
    #   app_store_connect: ValorantUI
    environment:
      # ios_signing:
      #   distribution_type: app_store
      #   bundle_identifier: com.larryyu.valorantui
      vars:
        XCODE_WORKSPACE: "iosApp/iosApp.xcworkspace"
        XCODE_SCHEME: "iosApp"
      xcode: latest
      cocoapods: default

    triggering:
      events:
        - tag
      branch_patterns:
        - pattern: 'release/*'
      cancel_previous_builds: true

    scripts:
      - name: Placeholder for App Store Build
        script: |
          echo "⚠️ This workflow requires:"
          echo "1. Apple Developer Account ($99/year)"
          echo "2. App Store Connect API Key"
          echo "3. Signing certificates"
          echo ""
          echo "For showcase/portfolio, use 'ios-simulator-workflow' instead"
          exit 0

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - omarkkhalil12@gmail.com

