workflows:
  kmm-android-workflow:
    name: KMM Android Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      java: 17
      groups:
        - google_credentials
      vars:
        PACKAGE_NAME: "com.larryyu.valorantui"
    scripts:
      - name: Set up local.properties
        script: echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Build Android APK
        script: |
          ./gradlew assembleDebug
          ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk
      - app/release/*.apk
    publishing:
      email:
        recipients:
          - omarkkhalil12@gmail.com
        notify:
          success: true
          failure: true

  kmm-ios-workflow:
    name: KMM iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      xcode: latest
      java: 17
    scripts:
      - name: Make gradlew executable
        script: |
          chmod +x gradlew

      - name: Build Kotlin Framework First
        script: |
          export XCODE_CONFIGURATION=Debug
          export NATIVE_ARCH=iosSimulatorArm64
          ./gradlew :composeApp:embedAndSignAppleFrameworkForXcode
          echo "Kotlin framework built"

      - name: Build iosApp for simulator
        script: |
          xcodebuild build \
            -project iosApp/iosApp.xcodeproj \
            -scheme iosApp \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,OS=17.5,name=iPhone 15 Pro' \
            -configuration Debug \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            -derivedDataPath build
    artifacts:
      - build/**/*.app
    publishing:
      email:
        recipients:
          - omarkkhalil12@gmail.com
        notify:
          success: true
          failure: true

