workflows:
  kmm-android-workflow:
    name: KMM Android Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      java: 17
      groups:
        - google_credentials
      vars:
        PACKAGE_NAME: "com.larryyu.valorantui"
    scripts:
      - name: Set up local.properties
        script: echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Build Android APK
        script: |
          ./gradlew assembleDebug
          ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk
      - app/release/*.apk
    publishing:
      email:
        recipients:
          - omarkkhalil12@gmail.com
        notify:
          success: true
          failure: true

  kmm-ios-workflow:
    name: KMM iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      xcode: latest
      java: 17
    scripts:
      - name: Make gradlew executable
        script: |
          chmod +x gradlew

      - name: Build Kotlin Framework First
        script: |
          export XCODE_CONFIGURATION=Debug
          export NATIVE_ARCH=iosSimulatorArm64
          ./gradlew :composeApp:embedAndSignAppleFrameworkForXcode
          echo "Kotlin framework built"

      - name: Build iosApp for simulator
        script: |
          xcodebuild build \
            -project iosApp/iosApp.xcodeproj \
            -scheme iosApp \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,OS=17.5,name=iPhone 15 Pro' \
            -configuration Debug \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            -derivedDataPath build
      - name: Take Screenshots
        script: |
          # Use specific simulator ID from available devices
          SIMULATOR_UDID="8014E13D-DF11-4689-9B55-08A818D29AD6"
          
          echo "Using simulator: iPhone 15 Pro (iOS 17.5)"
          echo "UDID: $SIMULATOR_UDID"
          
          # Boot simulator
          xcrun simctl boot $SIMULATOR_UDID 2>/dev/null || echo "Already booted"
          sleep 10
          
          # Find the app
          APP_PATH=$(find build -name "*.app" -type d | grep -v "Intermediates" | head -1)
          
          if [ -n "$APP_PATH" ]; then
            echo "Found app at: $APP_PATH"
            
            # Install app
            xcrun simctl install $SIMULATOR_UDID "$APP_PATH"
            sleep 2
            
            # Launch app
            xcrun simctl launch $SIMULATOR_UDID com.larryyu.valorantui
            sleep 5
            
            # Take screenshots
            mkdir -p screenshots/light screenshots/dark
            
            # Light mode
            xcrun simctl ui $SIMULATOR_UDID appearance light
            sleep 2
            xcrun simctl io $SIMULATOR_UDID screenshot screenshots/light/01_launch.png
            sleep 2
            xcrun simctl io $SIMULATOR_UDID screenshot screenshots/light/02_screen.png
            
            # Dark mode
            xcrun simctl ui $SIMULATOR_UDID appearance dark
            sleep 2
            xcrun simctl launch $SIMULATOR_UDID com.larryyu.valorantui
            sleep 3
            xcrun simctl io $SIMULATOR_UDID screenshot screenshots/dark/01_launch.png
            sleep 2
            xcrun simctl io $SIMULATOR_UDID screenshot screenshots/dark/02_screen.png
            
            echo "Screenshots taken successfully (light + dark mode)"
            ls -la screenshots/light/
            ls -la screenshots/dark/
          else
            echo "No app found to take screenshots"
            echo "Available build outputs:"
            find build -type d -name "*.app" | head -10
          fi
    artifacts:
      - build/**/*.app
      - screenshots/**/*.png
    publishing:
      email:
        recipients:
          - omarkkhalil12@gmail.com
        notify:
          success: true
          failure: true

