platform :ios, '14.1'

target 'iosApp' do
  use_frameworks!

  # Link the Kotlin Multiplatform framework
  pod 'ComposeApp', :path => '../composeApp'

  # Uncomment to enable Firebase Crashlytics (requires GoogleService-Info.plist)
  # pod 'Firebase/Core'
  # pod 'Firebase/Crashlytics'
  # pod 'Firebase/Analytics'
end

