platform :ios, '14.1'

target 'iosApp' do
  use_frameworks!

  # Link the Kotlin Multiplatform framework
  pod 'ComposeApp', :path => '../composeApp'

  # Firebase will be added back after CI/CD setup is complete
end

