platform :ios, '14.1'

target 'iosApp' do
  use_frameworks!

  # Link the Kotlin Multiplatform framework
  pod 'ComposeApp', :path => '../composeApp'

  # Firebase Crashlytics for crash reporting
  pod 'FirebaseCore', '~> 10.19.0'
  pod 'FirebaseCrashlytics', '~> 10.19.0'
  pod 'FirebaseAnalytics', '~> 10.19.0'
end

